# Generated by Django 4.1.7 on 2023-07-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viever', '0002_remove_user_name_user_date_creation_user_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('Новичек', 'Новичек'), ('ученик', 'ученик')], default='Новичек', max_length=50),
        ),
    ]
